CREATE TABLE IF NOT EXISTS Device (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id VARCHAR(255) NULL,
    location VARCHAR(255) NULL,
    map_point POINT NULL,
    delete_flag TINYINT(1) NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS Event (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    device_id BIGINT UNSIGNED NOT NULL,
    t0active DECIMAL(20, 6) NOT NULL,
    x_acc DOUBLE NOT NULL,
    y_acc DOUBLE NOT NULL,
    z_acc DOUBLE NOT NULL,
    createdat TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_event_device_time (device_id, t0active),
    CONSTRAINT fk_event_device FOREIGN KEY (device_id) REFERENCES Device (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
